import { UpdateTicketUseCase } from '../../../domain/ports/in/ticket/UpdateTicketUseCase';
import { Ticket, TicketStatus } from '../../../domain/models/Ticket';
import { TicketRepositoryPort } from '../../../domain/ports/out/TicketRepositoryPort';
import { NotFoundError } from '../../../domain/exceptions/NotFoundError';
import { TicketPayment } from '../../../domain/models/TicketPayment';

export class UpdateTicketUseCaseImpl implements UpdateTicketUseCase {
    constructor(private readonly ticketRepositoryPort: TicketRepositoryPort) {}

    async checkout(id: string, amount: number, paymentMethod: string, exitDate?: Date): Promise<Ticket> {
        const ticket = await this.ticketRepositoryPort.findById(id);
        if (!ticket) {
            throw new NotFoundError(`Ticket with ID ${id} not found.`);
        }

        if (ticket.status === TicketStatus.CLOSED) {
            throw new Error(`Ticket with ID ${id} is already closed.`);
        }

        ticket.exitDate = exitDate || new Date();
        ticket.status = TicketStatus.CLOSED;

        const payment = new TicketPayment(
            '', // ID generated by DB
            ticket,
            new Date(), // payment date
            amount,
            paymentMethod,
            ticket.parking
        );

        return this.ticketRepositoryPort.checkout(ticket, payment);
    }
}
